In [1]:
import numpy as np

In [45]:
a = np.empty([2, 3])

In [56]:
b = np.empty([3, 4])

In [57]:
a[0][0]

0.0

In [58]:
for i in range(2):
    for j in range(3):
        a[i][j] = i + j

In [59]:
for i in range(3):
    for j in range(4):
        b[i][j] = i - j

In [60]:
a

array([[ 0.,  1.,  2.],
       [ 1.,  2.,  3.]])

In [61]:
b

array([[ 0., -1., -2., -3.],
       [ 1.,  0., -1., -2.],
       [ 2.,  1.,  0., -1.]])

In [62]:
c = np.dot(a, b)

In [63]:
c

array([[  5.,   2.,  -1.,  -4.],
       [  8.,   2.,  -4., -10.]])